name: delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  image_picker: ^1.1.0
  geocoding: ^2.1.6  
  google_maps_flutter: ^2.13.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  get: ^4.7.2
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  cloudinary_public: 0.23.1

flutter:
  uses-material-design: true
